/mapora:
  ros__parameters:
    project_namespace: ytu_campus_080423_mapora
    pcap_dir_path: src/mapora/example_data/splitted_pcap
    pose_txt_path: src/mapora/example_data/ytu_campus_080423_pp_istn_utc_leo.txt
    las_export_directory: src/mapora/example_data/output_las/
    max_point_distance_from_lidar: 60.0  # in meters
    min_point_distance_from_lidar: 3.0  # in meters
    r_x: -179.643
    r_y: -0.404
    r_z: -0.778
